export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const DANG_KY_ACTION = "DANG_KY_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const GET_LIST_NGUOI_DUNG = "GET_LIST_NGUOI_DUNG";
export const GET_TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";
export const DELETE_NGUOI_DUNG = "DELETE_NGUOI_DUNG";
